# https://sidra.ibge.gov.br/pesquisa/cna/tabelas


# Tabela 6784 - Produto Interno Bruto, Produto Interno Bruto per capita, População residente e Deflator
[[tabelas]]
sidra_tabela = "6784"
territories = {1 = []}
