[[table]]
name        = "pevs_area_florestal"
schema      = "analytics"
strategy    = "replace"
sql         = "transform.sql"
description = "PEVS - área de florestas plantadas por tipo de floresta e município"
