SELECT
	P.ANO AS ANO,
	L.D1C AS ID_MUNICIPIO,
	L.D1N AS NOME_MUNICIPIO,
	DIM.D4N AS ESPECIE_FLORESTAL,
	DIM.MN AS UNIDADE,
	CASE
		WHEN D.V ~ '^-?[0-9]' THEN D.V::NUMERIC
	END AS AREA
FROM
	DADOS D
	JOIN PERIODO P ON D.PERIODO_ID = P.ID
	JOIN DIMENSAO DIM ON D.DIMENSAO_ID = DIM.ID
	JOIN LOCALIDADE L ON D.LOCALIDADE_ID = L.ID
WHERE
	D.TABELA_SIDRA_ID = '5930'
	AND D.ATIVO = TRUE;
