WITH
	LAVEOURAS_TEMPORARIAS AS (
		SELECT
			P.ANO AS ANO,
			L.D1C AS ID_MUNICIPIO,
			L.D1N AS NOME_MUNICIPIO,
			DIM.D4N AS PRODUTO,
			DIM.D2N AS VARIAVEL,
			DIM.MN AS UNIDADE,
			CASE
				WHEN D.V ~ '^-?[0-9]' THEN D.V::NUMERIC
			END AS VALOR
		FROM
			IBGE_SIDRA.DADOS D
			JOIN PERIODO P ON D.PERIODO_ID = P.ID
			JOIN DIMENSAO DIM ON D.DIMENSAO_ID = DIM.ID
			JOIN LOCALIDADE L ON D.LOCALIDADE_ID = L.ID
		WHERE
			1 = 1
			AND D.SIDRA_TABELA_ID IN ('839', '1000', '1001', '1002', '1612')
			AND D.ATIVO = TRUE
	)
SELECT
	ANO,
	ID_MUNICIPIO,
	NOME_MUNICIPIO,
	PRODUTO,
	SUM(
		CASE
			WHEN VARIAVEL = 'Área colhida' THEN VALOR
			ELSE 0
		END
	) AS AREA_COLHIDA,
	MAX(
		CASE
			WHEN VARIAVEL = 'Área colhida' THEN UNIDADE
		END
	) AS AREA_COLHIDA_UNIDADE,
	SUM(
		CASE
			WHEN VARIAVEL = 'Quantidade produzida' THEN VALOR
			ELSE 0
		END
	) AS QUANTIDADE_PRODUZIDA,
	MAX(
		CASE
			WHEN VARIAVEL = 'Quantidade produzida' THEN UNIDADE
		END
	) AS QUANTIDADE_PRODUZIDA_UNIDADE,
	SUM(
		CASE
			WHEN VARIAVEL = 'Rendimento médio da produção' THEN VALOR
			ELSE 0
		END
	) AS RENDIMENTO_MEDIO_PRODUCAO,
	MAX(
		CASE
			WHEN VARIAVEL = 'Rendimento médio da produção' THEN UNIDADE
		END
	) AS RENDIMENTO_MEDIO_PRODUCAO_UNIDADE,
	SUM(
		CASE
			WHEN VARIAVEL = 'Valor da produção' THEN VALOR
			ELSE 0
		END
	) AS VALOR_PRODUCAO,
	MAX(
		CASE
			WHEN VARIAVEL = 'Valor da produção' THEN UNIDADE
		END
	) AS VALOR_PRODUCAO_UNIDADE
FROM
	LAVEOURAS_TEMPORARIAS
GROUP BY
	ANO,
	ID_MUNICIPIO,
	NOME_MUNICIPIO,
	PRODUTO;
