# Tabela 6903 - Índice de Preços ao Produtor, por tipo de índice, indústria geral, indústrias extrativas e indústrias de transformação e atividades (dezembro de 2018 = 100)
[[tabelas]]
sidra_tabela = "6903"
variables = ["all"]
territories = {1 = []}
classifications = {842 = []}
