WITH
	DADOS_IPP_CNAE AS (
		SELECT
			P.DATA_INICIO AS PERIODO,
			L.NC AS NIVEL_TERRITORIAL_ID,
			L.NN AS NIVEL_TERRITORIAL,
			L.D1C AS LOCALIDADE_ID,
			L.D1N AS LOCALIDADE,
			DIM.D4C AS SETOR_ID,
			DIM.D4N AS SETOR,
			DIM.D2N AS VARIAVEL,
			DIM.MN AS UNIDADE,
			CASE
				WHEN D.V ~ '^-?[0-9]' THEN D.V::NUMERIC
			END AS VALOR
		FROM
			DADOS D
			JOIN PERIODO P ON D.PERIODO_ID = P.ID
			JOIN DIMENSAO DIM ON D.DIMENSAO_ID = DIM.ID
			JOIN LOCALIDADE L ON D.LOCALIDADE_ID = L.ID
		WHERE
			D.TABELA_SIDRA_ID = '6903'
			AND D.ATIVO = TRUE
	)
SELECT
	PERIODO,
	NIVEL_TERRITORIAL_ID,
	NIVEL_TERRITORIAL,
	LOCALIDADE_ID,
	LOCALIDADE,
	SETOR_ID,
	SETOR,
	MAX(
		CASE
			WHEN VARIAVEL = 'IPP - Número-índice (dezembro de 2018 = 100)' THEN VALOR
		END
	) AS IPP_NUMERO_INDICE,
	MAX(
		CASE
			WHEN VARIAVEL = 'IPP - Número-índice (dezembro de 2018 = 100)' THEN UNIDADE
		END
	) AS IPP_NUMERO_INDICE_UNIDADE,
	MAX(
		CASE
			WHEN VARIAVEL = 'IPP - Variação acumulada no ano (em relação a dezembro do ano anterior)' THEN VALOR
		END
	) AS IPP_VARIACAO_ACUMULADA_ANO,
	MAX(
		CASE
			WHEN VARIAVEL = 'IPP - Variação acumulada no ano (em relação a dezembro do ano anterior)' THEN UNIDADE
		END
	) AS IPP_VARIACAO_ACUMULADA_ANO_UNIDADE,
	MAX(
		CASE
			WHEN VARIAVEL = 'IPP - Variação mês/mês imediatamente anterior (M/M-1)' THEN VALOR
		END
	) AS IPP_VARIACAO_MES_MES_ANTERIOR,
	MAX(
		CASE
			WHEN VARIAVEL = 'IPP - Variação mês/mês imediatamente anterior (M/M-1)' THEN UNIDADE
		END
	) AS IPP_VARIACAO_MES_MES_ANTERIOR_UNIDADE,
	MAX(
		CASE
			WHEN VARIAVEL = 'IPP - Variação mês/mesmo mês do ano anterior (M/M-12)' THEN VALOR
		END
	) AS IPP_VARIACAO_MES_ANO_ANTERIOR,
	MAX(
		CASE
			WHEN VARIAVEL = 'IPP - Variação mês/mesmo mês do ano anterior (M/M-12)' THEN UNIDADE
		END
	) AS IPP_VARIACAO_MES_ANO_ANTERIOR_UNIDADE
FROM
	DADOS_IPP_CNAE
GROUP BY
	PERIODO,
	NIVEL_TERRITORIAL_ID,
	NIVEL_TERRITORIAL,
	LOCALIDADE_ID,
	LOCALIDADE,
	SETOR_ID,
	SETOR;
