# Pesquisa da Pecuária Municipal - Aquicultura e Exploração Animal
# https://sidra.ibge.gov.br/pesquisa/ppm/tabelas

# Tabela 94 - Vacas ordenhadas e quantidade de leite produzida,
#             por tipo de estabelecimento
[[tabelas]]
tabela_sidra = "94"
variables = ["allxp"]
territories = {6 = []}

# Tabela 95 - Ovinos tosquiados nos estabelecimentos agropecuários
#             e quantidade de lã produzida
[[tabelas]]
tabela_sidra = "95"
variables = ["allxp"]
territories = {6 = []}
