SELECT
	P.ANO AS ANO,
	L.D1C AS ID_MUNICIPIO,
	CASE DIM.D2N
		WHEN 'Ovinos tosquiados nos estabelecimentos agropecuários' THEN 'Ovinos tosquiados'
		ELSE DIM.D2N
	END AS VARIAVEL,
	DIM.MN AS UNIDADE,
	CASE
		WHEN D.V ~ '^-?[0-9]' THEN D.V::NUMERIC
	END AS VALOR
FROM
	DADOS D
	JOIN PERIODO P ON D.PERIODO_ID = P.ID
	JOIN DIMENSAO DIM ON D.DIMENSAO_ID = DIM.ID
	JOIN LOCALIDADE L ON D.LOCALIDADE_ID = L.ID
WHERE
	1 = 1
	AND D.SIDRA_TABELA_ID IN ('94', '95')
	AND D.ATIVO = TRUE;
