SELECT
	P.ANO AS ANO,
	L.D1C AS ID_MUNICIPIO,
	L.D1N AS NOME_MUNICIPIO,
	MAX(CASE WHEN D.TABELA_SIDRA_ID = '94' THEN CASE WHEN D.V ~ '^-?[0-9]' THEN D.V::NUMERIC END END) AS VACAS_ORDENHADAS,
	MAX(CASE WHEN D.TABELA_SIDRA_ID = '95' THEN CASE WHEN D.V ~ '^-?[0-9]' THEN D.V::NUMERIC END END) AS OVINOS_TOSQUIADOS
FROM
	DADOS D
	JOIN PERIODO P ON D.PERIODO_ID = P.ID
	JOIN LOCALIDADE L ON D.LOCALIDADE_ID = L.ID
WHERE
	D.TABELA_SIDRA_ID IN ('94', '95')
	AND D.ATIVO = TRUE
GROUP BY
	ANO,
	ID_MUNICIPIO,
	NOME_MUNICIPIO;
