# Tabela 8885 - Produção Física Industrial, por grupos e classes industriais selecionados
[[tabelas]]
sidra_tabela = "8885"
territories = {1 = []}


# Tabela 8886 - Produção Física Industrial dos insumos típicos da construção civil
[[tabelas]]
sidra_tabela = "8886"
territories = {1 = []}


# Tabela 8887 - Produção Física Industrial, por grandes categorias econômicas
[[tabelas]]
sidra_tabela = "8887"
territories = {1 = []}


# Tabela 8888 - Produção Física Industrial, por seções e atividades industriais
[[tabelas]]
sidra_tabela = "8888"
territories = {1 = []}


# Tabela 8889 - Produção Física Industrial, por indicadores especiais
[[tabelas]]
sidra_tabela = "8889"
territories = {1 = []}
