SELECT
	P.ANO AS ANO,
	L.D1C AS ID_MUNICIPIO,
	L.D1N AS NOME_MUNICIPIO,
	CASE
		WHEN D.V ~ '^-?[0-9]' THEN D.V::NUMERIC
	END AS N_PESSOAS
FROM
	DADOS D
	JOIN PERIODO P ON D.PERIODO_ID = P.ID
	JOIN DIMENSAO DIM ON D.DIMENSAO_ID = DIM.ID
	JOIN LOCALIDADE L ON D.LOCALIDADE_ID = L.ID
WHERE
	D.TABELA_SIDRA_ID IN ('305', '793')
	AND D.ATIVO = TRUE
