SELECT
	P.DATA_INICIO AS PERIODO,
	L.NC AS ID_NIVEL_LOCALIDADE,
	L.NN AS NOME_NIVEL_LOCALIDADE,
	L.D1C AS ID_LOCALIDADE,
	L.D1N AS NOME_LOCALIDADE,
	DIM.D2N AS VARIAVEL,
	DIM.D4N AS TIPO,
	DIM.D5N AS ACABAMENTO,
	DIM.MN AS UNIDADE,
	CASE
		WHEN D.V ~ '^-?[0-9]' THEN D.V::NUMERIC
	END AS CUSTO_PROJETO
FROM
	DADOS D
	JOIN PERIODO P ON D.PERIODO_ID = P.ID
	JOIN DIMENSAO DIM ON D.DIMENSAO_ID = DIM.ID
	JOIN LOCALIDADE L ON D.LOCALIDADE_ID = L.ID
WHERE
	1 = 1
	AND D.SIDRA_TABELA_ID = '647'
	AND D.ATIVO = TRUE;
