WITH
	DADOS_INPC AS (
		SELECT
			P.DATA_INICIO AS PERIODO,
			L.NC AS NIVEL_TERRITORIAL_ID,
			L.NN AS NIVEL_TERRITORIAL,
			L.D1C AS LOCALIDADE_ID,
			L.D1N AS LOCALIDADE,
			DIM.D2C AS VARIAVEL_ID,
			DIM.D2N AS VARIAVEL,
			DIM.MC AS UNIDADE_ID,
			DIM.MN AS UNIDADE,
			DIM.D4C AS ITEM_ID,
			DIM.D4N AS ITEM,
			CASE
				WHEN D.V ~ '^-?[0-9]' THEN D.V::NUMERIC
			END AS VALOR
		FROM
			DADOS D
			JOIN PERIODO P ON D.PERIODO_ID = P.ID
			JOIN DIMENSAO DIM ON D.DIMENSAO_ID = DIM.ID
			JOIN LOCALIDADE L ON D.LOCALIDADE_ID = L.ID
		WHERE
			D.SIDRA_TABELA_ID IN (
				'1686',
				'1690', -- jul/1989 - dez/1990
				'22',
				'23', -- jan/1991 - jul/1999
				'653',
				'654', -- ago/1999 - jun/2006
				'2951', -- jul/2006 - dez/2011
				'1100', -- jan/2012 - dez/2019
				'7063' -- jan/2020 em diante
			)
			AND D.ATIVO = TRUE
	),
	TRATADO AS (
		SELECT
			PERIODO,
			NIVEL_TERRITORIAL_ID,
			NIVEL_TERRITORIAL,
			LOCALIDADE_ID,
			LOCALIDADE,
			UNIDADE_ID,
			UNIDADE,
			ITEM_ID,
			(
				CASE ITEM
					WHEN 'Índice geral' THEN '0'
					ELSE SPLIT_PART(ITEM, '.', 1)
				END
			) CODIGO_ITEM,
			(
				CASE ITEM
					WHEN 'Índice geral' THEN 'Índice geral'
					ELSE SPLIT_PART(ITEM, '.', 2)
				END
			) NOME_ITEM,
			SUM(
				CASE
					WHEN VARIAVEL = 'INPC - Peso mensal' THEN VALOR
					ELSE NULL
				END
			) PESO,
			SUM(
				CASE
					WHEN VARIAVEL = 'INPC - Variação mensal' THEN VALOR
					ELSE NULL
				END
			) VARIACAO
		FROM
			DADOS_INPC
		GROUP BY
			PERIODO,
			NIVEL_TERRITORIAL_ID,
			NIVEL_TERRITORIAL,
			LOCALIDADE_ID,
			LOCALIDADE,
			UNIDADE_ID,
			UNIDADE,
			ITEM_ID,
			CODIGO_ITEM,
			NOME_ITEM
	)
SELECT
	PERIODO,
	NIVEL_TERRITORIAL_ID,
	NIVEL_TERRITORIAL,
	LOCALIDADE_ID,
	LOCALIDADE,
	UNIDADE_ID,
	UNIDADE,
	ITEM_ID,
	CODIGO_ITEM,
	NOME_ITEM,
	(
		CASE
			WHEN CODIGO_ITEM = '0' THEN 0
			ELSE LENGTH(CODIGO_ITEM)
		END
	) AS NIVEL,
	PESO,
	VARIACAO
FROM
	TRATADO;
