# https://sidra.ibge.gov.br/pesquisa/leite/tabelas


# Tabela 1086 - Número de informantes e Quantidade de leite cru, resfriado ou não, adquirido e industrializado, no mês e no trimestre, por tipo de inspeção
[[tabelas]]
sidra_tabela = "1086"
variables = ["all"]
territories = {3 = []}
